live_config_reload = true

import = [
  "~/.config/alacritty/themes/catppuccin-latte.toml"
]

[font]
size = 17.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1.0
blur = false

[window.padding]
x = 15
y = 20
